// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBG55ewagqfZip1u42VTdVX0gohsHvnCM',
    appId: '1:393789698670:web:2c609612dfd5dc2195ac7f',
    messagingSenderId: '393789698670',
    projectId: 'payhab',
    authDomain: 'payhab.firebaseapp.com',
    storageBucket: 'payhab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkaz899vAxD50axFQQpDDOP5eoL4CoBTQ',
    appId: '1:393789698670:android:cb93655560a4074f95ac7f',
    messagingSenderId: '393789698670',
    projectId: 'payhab',
    storageBucket: 'payhab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZ_9zyBB4F_kmrz8_ecpjcuAMsEmY1_E',
    appId: '1:393789698670:ios:6fe82a6f15d815e195ac7f',
    messagingSenderId: '393789698670',
    projectId: 'payhab',
    storageBucket: 'payhab.firebasestorage.app',
    iosBundleId: 'com.example.payhab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzZ_9zyBB4F_kmrz8_ecpjcuAMsEmY1_E',
    appId: '1:393789698670:ios:6fe82a6f15d815e195ac7f',
    messagingSenderId: '393789698670',
    projectId: 'payhab',
    storageBucket: 'payhab.firebasestorage.app',
    iosBundleId: 'com.example.payhab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBG55ewagqfZip1u42VTdVX0gohsHvnCM',
    appId: '1:393789698670:web:6e631a716d3dac7395ac7f',
    messagingSenderId: '393789698670',
    projectId: 'payhab',
    authDomain: 'payhab.firebaseapp.com',
    storageBucket: 'payhab.firebasestorage.app',
  );
}
